TITLE

Implementation of Lex Program using LEX Tool

AIM

To study and implement a lexical analyzer using LEX tool.

THEORY

LEX is a tool used to generate lexical analyzers. It takes a set of rules as input and produces a program (usually in C) that can recognize patterns in text. These patterns are defined using regular expressions, and each pattern is associated with an action to be performed when it is matched.

A LEX program consists of three main sections:

Definition Section: Contains declarations of variables and regular definitions
Rules Section: Contains patterns and corresponding actions
User Subroutines Section: Contains additional C code, including the main() function

The lexical analyzer generated by LEX reads the input character by character and matches it with the given patterns. When a match is found, the corresponding action is executed.

LEX is often used with YACC, which handles syntax analysis. While LEX identifies tokens, YACC uses those tokens to check grammatical structure.




%{
#include <stdio.h>
int keywords = 0, identifiers = 0, numbers = 0, operators = 0;
%}

digit      [0-9]
letter     [a-zA-Z]
id         {letter}({letter}|{digit})*

%%

"int"|"float"|"if"|"else"|"while"|"return"   {
    printf("Keyword: %s\n", yytext);
    keywords++;
}

{id}    {
    printf("Identifier: %s\n", yytext);
    identifiers++;
}

{digit}+    {
    printf("Number: %s\n", yytext);
    numbers++;
}

"+"|"-"|"*"|"/"|"="    {
    printf("Operator: %s\n", yytext);
    operators++;
}

[ \t\n]+   ;   // ignore whitespace

.   {
    printf("Invalid: %s\n", yytext);
}

%%

int main() {
    printf("Enter input:\n");
    yylex();

    printf("\nSummary:\n");
    printf("Keywords: %d\n", keywords);
    printf("Identifiers: %d\n", identifiers);
    printf("Numbers: %d\n", numbers);
    printf("Operators: %d\n", operators);

    return 0;
}

int yywrap() {
    return 1;
}